### ISSUE TITLE
Revision 1 checklist

### ISSUE THREAD

**Issue by anders-kolstad** [anders-kolstad/aggregationPathways#2]
- [ ] More references. In general, but esp regarding terminology, WFD, nature index.
- [ ] Would be good to get further with IndiMap so we can refer back to that work on how inconsistent terminology and lack of documentation can be a problem. But maybe we can find something in other reviews Grover et al, Lange et al, Cummins et al, and more.
- [ ] Lots of typoes
- [ ] I think I would like more on the topic of aggregating variables and reporting both aggregated variables and indicators side by side. 
- [ ] Also we can add more examples where rethinking the variable itself is perhaps the best option when spatial aggregation becomes troublesome. E.g. using densities rather than absolute numbers.

**Comment by anders-kolstad** [comment]
Allain et al would call the normalisation process (scaling, truncations and transforming) for customisation.

**Comment by anders-kolstad** [comment]
Spatiall aggregation, the conversion of fine-scale data (and somthime 'information' sensu Alain et al 2018) into coraser-resolution data, changes the scale and the meaning of the metric,

**Comment by anders-kolstad** [comment]
Consider putting the example indicators in a table similar to table 2 in Allain et al 2018.

**Comment by anders-kolstad** [comment]
Aggregating variables could be quite a bit more 'dangerous' than aggretaing indicators. The reason being that normalisation can take up some of the local context via the referece levels, and thu become more scale independent, whereas aggregating variables homogenises local variation to a greater extent.

**Comment by anders-kolstad** [comment]
Spatiall aggregation generally increase tangibility, but decreases an indicators use as a source for debate and learning. The degree of aggregation therefore mush match the objective of the indicator, wheter it is to report number to an ecosystem account, or to inform an ecosystem assessment/evaluation, or to guide spatial planning , etc.
